name: unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.4"
        
      - name: Run tests
        run: swift test
